inc_aarpPartnerToolbarTabless_js =
'<style type="text/css" media="all">\n<!--//\n\ndiv#aarpPart'
+ 'nerToolbar {\n	margin: 0;\n	padding: 0;\n}\n\ndiv#aarpPartner'
+ 'Toolbar {\n	border-bottom:4px solid #6b6b6b;\n	margin: 0;\n'
+ '	padding: 0;\n	width: 770px;\n	margin-bottom: 0;\n	font: 76'
+ '% Arial, Verdana, Helvetica, sans-serif;	\n}\ndiv#aarpPart'
+ 'nerToolbar, #languageToggle, #brandingSearch, #logo {\n	p'
+ 'osition: relative;\n}\ndiv#aarpPartnerToolbar div.clearer '
+ '{\n	clear: both;\n	line-height: 0;\n}\n#aarpPartnerToolbar a'
+ ':link {\n	color: #009;\n	padding: 2px;\n}\n#aarpPartnerToolb'
+ 'ar a:visited {\n	color: #909;\n	padding: 2px;\n}\n#aarpPartn'
+ 'erToolbar a:hover {\n	color: #FFF;\n	padding: 2px;\n	text-d'
+ 'ecoration: none;\n	background: #009;\n}\n#aarpPartnerToolba'
+ 'r a:active {\n	color: #FFF;\n	padding: 2px;\n	text-decorati'
+ 'on: none;\n	background: #909;\n}\n#aarpPartnerToolbar a.but'
+ 'ton:link, div#aarpPartnerToolbar a.button:hover, div#aar'
+ 'pPartnerToolbar a.button:active, div#aarpPartnerToolbar '
+ 'a.button:visited {\n	padding: 0;\n	text-decoration: none;\n'
+ '	background: transparent;\n}\n\ndiv#aarpPartnerToolbar * {\n'
+ '	font-family: Arial, Verdana, Helvetica, sans-serif;\n\n}\n'
+ '\ndiv#aarpPartnerToolbar ol, ul, li {\n	'
+ 'Arial, Verdana, Helvetica, sans-serif;\n	margin-top: 0.2e'
+ 'm;\n	margin-bottom: 0.1em;\n	text-align: left;\n}\n\ndiv#aarp'
+ 'PartnerToolbar li > p {\n	margin-top: 0.2em;\n}\n\n#globalNa'
+ 'v {\n	color: #FFF;\n	font-size: 0.99em;\n	padding: 2px;\n	ba'
+ 'ckground: #6B6B6B;\n\n}\n#globalNav a:link, #globalNav a:vi'
+ 'sited {\n	color: #FFF;\n	text-decoration: underline;\n	font'
+ '-weight: bold;\n	padding: 2px;\n}\n#globalNav a:hover, #glo'
+ 'balNav a:active {\n	color: #6B6B6B;\n	background: #FFF;\n}\n'
+ 'div#aarpPartnerToolbar #languageToggle {\n	float: right;\n'
+ '}\n#brandingSearch {\n	border-top: dotted 2px #333;\n	paddi'
+ 'ng: 6px 11px;\n	text-align: right;\n	color: #424141;\n	back'
+ 'ground: #FFF;\n}\n#brandingSearch a:link, #brandingSearch '
+ 'a:visited {\n	padding: 2px;\n	color: #424141;\n}\n#brandingS'
+ 'earch a:hover, #brandingSearch a:active {\n	padding: 2px;'
+ '\n	color: #FFF;\n	background: #424141;\n}\ndiv#aarpPartnerTo'
+ 'olbar #logo {\n	float: left;\n}\n#brandingSearch #search {\n'
+ '	margin-top: 20px;\n	font-size: 1.0em;\n	color: #000;\n}\n#b'
+ 'randingSearch #keywords {\n	width: 205px;\n	font-size: 11p'
+ 'x;\n	font-weight: normal;\n}\n#brandingSearch #go {\n	vertic'
+ 'al-align: top;\n	width: 42px;\n	height: 24px;\n}\n#topicNav '
+ '{\n	margin: 0;\n	padding: 0;\n	border: none;\n}\nul#toolbar, '
+ 'ul#toolbar li {\n	margin: 0;\n	padding: 0;\n	border: none;\n'
+ '}\nul#toolbar {\n	list-style-type: none;\n}\nul#toolbar li {'
+ '\n	float: left;\n}\nul#toolbar li a {\n	display: block;\n	hei'
+ 'ght: 50px;\n}\nul#toolbar li a span {\n	display: none;\n}\nul'
+ '#toolbar li#n-msd a {\n	width: 121px;\n	background: url(ht'
+ 'tp://assets.aarp.org/www.aarp.org_/build/templates/style'
+ '/toolbar.gif);\n}\nul#toolbar li#n-msd a:hover, ul#toolbar'
+ ' li#n-msd a.active {\n	background-position: 0 -50px;\n}\nul'
+ '#toolbar li#n-leg a {\n	width: 90px;\n	background: url(htt'
+ 'p://assets.aarp.org/www.aarp.org_/build/templates/style/'
+ 'toolbar.gif) -125px 0;\n}\nul#toolbar li#n-leg a:hover, ul'
+ '#toolbar li#n-leg a.active {\n	background: url(https://ass'
+ 'ets.aarp.org/www.aarp.org_/build/templates/style/toolbar'
+ '.gif) -125px -50px;\n}\nul#toolbar li#n-learntech a {\n	wid'
+ 'th: 91px;\n	background: url(https://assets.aarp.org/www.aa'
+ 'rp.org_/build/templates/style/toolbar.gif) -219px 0;\n}\nu'
+ 'l#toolbar li#n-learntech a:hover, ul#toolbar li#n-learnt'
+ 'ech a.active {\n	background: url(https://assets.aarp.org/w'
+ 'ww.aarp.org_/build/templates/style/toolbar.gif) -219px -'
+ '50px;\n}\nul#toolbar li#n-health a {\n	width: 85px;\n	backgr'
+ 'ound: url(https://assets.aarp.org/www.aarp.org_/build/tem'
+ 'plates/style/toolbar.gif) -314px 0;\n}\nul#toolbar li#n-he'
+ 'alth a:hover, ul#toolbar li#n-health a.active {\n	backgro'
+ 'und: url(https://assets.aarp.org/www.aarp.org_/build/temp'
+ 'lates/style/toolbar.gif) -314px -50px;\n}\nul#toolbar li#n'
+ '-life a {\n	width: 90px;\n	background: url(https://assets.a'
+ 'arp.org/www.aarp.org_/build/templates/style/toolbar.gif)'
+ ' -403px 0;\n}\nul#toolbar li#n-life a:hover, ul#toolbar li'
+ '#n-life a.active {\n	background: url(https://assets.aarp.o'
+ 'rg/www.aarp.org_/build/templates/style/toolbar.gif) -403'
+ 'px -50px;\n}\nul#toolbar li#n-money a {\n	width: 91px;\n	bac'
+ 'kground: url(https://assets.aarp.org/www.aarp.org_/build/'
+ 'templates/style/toolbar.gif) -497px 0;\n}\nul#toolbar li#n'
+ '-money a:hover, ul#toolbar li#n-money a.active {\n	backgr'
+ 'ound: url(https://assets.aarp.org/www.aarp.org_/build/tem'
+ 'plates/style/toolbar.gif) -497px -50px;\n}\nul#toolbar li#'
+ 'n-travel a {\n	width: 85px;\n	background: url(https://asset'
+ 's.aarp.org/www.aarp.org_/build/templates/style/toolbar.g'
+ 'if) -592px 0;\n}\nul#toolbar li#n-travel a:hover, ul#toolb'
+ 'ar li#n-travel a.active {\n	background: url(https://assets'
+ '.aarp.org/www.aarp.org_/build/templates/style/toolbar.gi'
+ 'f) -592px -50px;\n}\nul#toolbar li#n-leisure a {\n	width: 8'
+ '4px;\n	background: url(https://assets.aarp.org/www.aarp.or'
+ 'g_/build/templates/style/toolbar.gif) -681px 0;\n}\nul#too'
+ 'lbar li#n-leisure a:hover, ul#toolbar li#n-leisure a.act'
+ 'ive {\n	background: url(https://assets.aarp.org/www.aarp.o'
+ 'rg_/build/templates/style/toolbar.gif) -681px -50px;\n}\nd'
+ 'iv#aarpPartnerToolbar img {\n	border: 0;\n}\ndiv#aarpPartne'
+ 'rToolbar ol, ul, li {\n	font-size: 100%;\n	line-height: 120'
+ '%;\n}\n// -->\n</style>\n\n<div id="aarpPartnerToolbar">\n	<di'
+ 'v id="globalNav">\n		<a name="top"></a><a href="http://ww'
+ 'w.aarp.org/">AARP Home</a> &nbsp;|&nbsp; <a href="http:/'
+ '/www.aarp.org/about_aarp/contact/">Contact AARP</a> &nbs'
+ 'p;|&nbsp; <a href="http://www.aarp.org/sitemap/">Site Ma'
+ 'p</a>\n	</div><!-- /globalNav -->\n\n	\n	\n	<div id="branding'
+ 'Search">\n		<a class="button" href="http://www.aarp.org/"'
+ '><img src="https://assets.aarp.org/www.aarp.org_/build/te'
+ 'mplates/style/aarpLogo.gif" id="logo" alt="AARP: The Pow'
+ 'er to Make it Better (tm)" /></a>\n		<a href="http://www.'
+ 'aarp.org/research/">Policy &amp; Research</a> &nbsp;|&nb'
+ 'sp; <a href="http://www.aarpmagazine.org">AARP The Magaz'
+ 'ine</a>\n		&nbsp;|&nbsp; <a href="http://www.aarp.org/bul'
+ 'letin/">AARP Bulletin</a>\n		\n		\n		<form id="search" meth'
+ 'od="get" action="https://www.aarp.org/search_advanced/sea'
+ 'rch_results.html" name="searchform">\n        <input type'
+ '="hidden" name="config" value="htdig_www_aarp_org_small"'
+ '>\n		<div>\n		&nbsp;\n		<!--\n		SEARCH\n		<input type="text" '
+ 'size="12" name="words" id="keywords" />\n		<input id="go"'
+ ' type="image" src="https://assets.aarp.org/www.aarp.org_/'
+ 'build/templates/style/go.gif" value="GO" />\n		-->\n		</di'
+ 'v>\n		</form>\n		\n	</div>\n	<!-- /brandingSearch -->\n	\n\n\n	<'
+ 'div class="clearer" style="height:3px;"></div>\n	\n</div><'
+ '!-- /header -->\n';

// end_var_declaration
document.write(inc_aarpPartnerToolbarTabless_js);