
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Medicare-Approved Drug Discount Card Enrollment Help</title>
</head>

<body>
<form>
				<input type="button" value="Print This Page" onClick="print();">
</form>
<p class="MsoNormal"><b>&ldquo;Step 1: Preliminary Questions&rdquo; Page Help</b></p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Confirm that the Medicare-Approved Drug Discount Card you selected is listed.&nbsp;&nbsp; </p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Once you have answered each of the questions, you must click on the &ldquo;Continue&rdquo; button to proceed to Step 2.</p>
<p class="MsoNormal"><b>&nbsp;&ldquo;Step 2: Confirm Responses&rdquo; Page Help</b></p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Check your responses carefully.&nbsp; If you need to change any of your responses, click on the &ldquo;Change Responses&rdquo; button.&nbsp; If your responses are correct, click on the &ldquo;Enroll with Medicare.gov&rdquo; button.&nbsp; </p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Once you&rsquo;ve clicked on the &ldquo;Enroll with Medicare.gov&rdquo; button, you will leave the BenefitsCheckUpRx web site and enter Medicare&rsquo;s web site for on-line enrolling for the Medicare-approved drug discount card you selected.</p>
<p class="MsoNormal"><b>&ldquo;Start Enrollment&rdquo; Page Help</b></p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>You must fill out all of the Personal Information.&nbsp; Some of the information you answered in the &ldquo;Preliminary Questions&rdquo; section will already be filled in on this page.&nbsp; If you do not answer all of the required questions, you will be prompted to do so before continuing to the next page.&nbsp; </p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>The &ldquo;Medicare/HICN Number&rdquo; has four boxes you must fill out.&nbsp; You will find this number on your Medicare Red, White and Blue card.&nbsp; The first three boxes require numbers to be answered  and the last field is a letter (for example,  111-22-333-A)</p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>When your personal information is entered completely, click the &ldquo;Continue&rdquo; button.</p>
<p class="MsoNormal"><b>&ldquo;Confirm Enrollment Information&rdquo; Page Help</b></p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Check your Personal Information carefully.&nbsp; If you need to change the information you&rsquo;ve entered, click on the &ldquo;Edit&rdquo; button, change your information and click the &ldquo;Continue&rdquo; button.&nbsp; </p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>After you have reviewed your Personal Information, and you are ready to enroll with the Card, you must click on the &ldquo;Enroll Now&rdquo; button, and you will be prompted with a window asking, &ldquo;Are you sure you want to proceed?&rdquo; Once you have clicked yes, your enrollment will be sent to the Card Company. </p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>If you do not wish to enroll with the Card, you can click on the &ldquo;Decline&rdquo; button and you will be brought to the &ldquo;Enrollment Incomplete&rdquo; Page.</p>
<p class="MsoNormal"><b>&ldquo;Enrollment Incomplete&rdquo; Page Help</b></p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>If you click on the &ldquo;Back&rdquo; button, you will be brought back to the &ldquo;Confirm Enrollment Information&rdquo; Page.</p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>If you wish to return to BenefitsCheckUpRx from this page, you must click on the &ldquo;Back&rdquo; button (or the button on your browser that allows you to go back to your previously viewed pages) on the top left corner of your page until you return to the &ldquo;Our Recommendations&rdquo; or &ldquo;Application Guide&rdquo; page of BenefitsCheckUpRx.&nbsp; (In some instances, you may have to click on this button several times to return to BenefitsCheckUpRx.)</p>
<p class="MsoNormal"><b>&ldquo;Confirmation&rdquo; Page Help</b></p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>You will see a confirmation number on the top of the page.&nbsp; It is important that you either print this page for your records or write down the confirmation number.&nbsp; You will also see a contact number for the Card Company where you applied.</p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>You should receive information from the card company shortly.</p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Should you have additional questions, you may call 1-800-MEDICARE for assistance.</p>
<p class="MsoNormal" style="margin-left: 0.5in; text-indent: -0.25in;"><span style="font-family: Symbol;">&middot;<span style="font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Once you click on the &ldquo;Continue&rdquo; button, you will be brought back to BenefitsCheckUpRx where you can click on a link to return to your BenefitsCheckUpRx Recommendations. </p>
</body>
</html>