<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Write ZIP Check JavaScript File</title>
</head>

<body>
<cfset strOutData = "// Do not edit.  This file is automatically generated.
// Last generated: " & DateFormat(Now()) & " " & TimeFormat(Now()) & "

function isZipInState(zip, state) {
	switch (state) {
">
<cfloop index="stateID" list="AK,AL,AR,AZ,CA,CO,CT,DE,DC,FL,GA,HI,IA,ID,IL,IN,KS,KY,LA,MA,MD,ME,MI,MN,MO,MS,MT,NC,ND,NE,NH,NJ,NM,NV,NY,OH,OK,OR,PA,RI,SC,SD,TN,TX,UT,VA,VT,WA,WI,WV,WY">
	<cfquery name="zip" datasource="#application.dbSrc#">
		select zipcode
		from zip
		where state_id='#stateID#'
			and valid=1
		order by zipcode
	</cfquery>
	<cfoutput>Writing '#stateID#' case.<br /></cfoutput>
	<cfset strOutData = strOutData & "		case '#stateID#':
			return '#ValueList(zip.zipcode)#'.indexOf(zip);
			break;
">
</cfloop>
<cfset strOutData = strOutData & "		default:
			return -1;
			break;
	}
}
">
<cffile action="WRITE" file="#session.strIncludePath#ziplist.js" output="#strOutData#">

</body>
</html>
