<cfquery dataSource="#APPLICATION.dsn#">
UPDATE display_language
SET display_text = '<b>How can this program help me?</b><br>  Supplemental Security Income (SSI) is a federal program that provides cash benefits every month if you meet the program guidelines.  The amount you get will be determined by the amount of income you receive from other sources and your living arrangements.  The purpose of the program is to make sure you have a minimum level of income so that you can pay for basic needs such as: food, clothing, and shelter. <br>  <br>  <b>Please note:</b>  If you enroll in both Medicare and SSI, you will be signed up for the Extra Help program through Medicare Prescription Drug Coverage. This program helps people with limited income and resources pay for their medicines. <br>  <br>  <b>Can I apply?</b><br>  You may get help from this program if you blind or disabled.  In addition, you must have limited income and resources.  Some resources such as your home, car, and certain portions of life insurance and burial accounts may not be counted when determining whether you meet the program guidelines. <br>  <br>  If you are a U.S. citizen and meet the other program guidelines, you may get help from this program. Some people who are not U.S. citizens may also take part in the program. You should contact the <a href="http://www.ssa.gov/pubs/11051.html" target="_blank"> Social Security Administration</a> for more information about SSI’s citizenship rules.<br>  <br>  <b>How do I apply?</b><br>  If you need help applying for SSI, Human Arc, a partner of the National Council on Aging, can help you apply for the program.  Human Arc&rsquo;s professional Disability Specialists can help with first-time applications, appeals and denials.  You can contact a Human Arc Disability Specialist by calling or visiting their Web site below.<br>    <img src="https://www.benefitscheckup.org/cf/img/partners/logo_humanarc.gif"><br>  <b>Human Arc</b><br>  Toll-free: (888) 825-1544  <br>Web site: [[track|humanarc|http://www.humanarc.com/disability/referrals.html?ekfrm=692]]  <br>  <br>  <b>Please note:</b>  The Social Security Administration (SSA) counts the date of a request for benefits as the filing date of the application. This is important because the date of the application will determine when your benefits start.  Unless you can submit a full application today, you should call SSA immediately and say that you want to apply for Supplemental Security Income benefits.  After the call, you can send them a letter like this: <a href="http://www.benefitscheckup.org/cf/frmssiprotected.pdf" target="_blank">Protected Filing Date Letter</a>.  You must submit a completed application to SSA within 60 days of the date of your request in order to get program benefits.'
WHERE display_id = 80651
AND language_id = 'EN';
</cfquery>

<cfquery dataSource="#APPLICATION.dsn#">
UPDATE display_language
SET display_text = '<b>How can this program help me?</b><br>  Supplemental Security Income (SSI) is a federal program that provides cash benefits every month if you meet the program guidelines.  The amount you get will be determined by the amount of income you receive from other sources and your living arrangements.  The purpose of the program is to make sure you have a minimum level of income so that you can pay for basic needs such as: food, clothing, and shelter. <br>  <br>  <b>Please note:</b>  If you enroll in both Medicare and SSI, you will be signed up for the Extra Help program through Medicare Prescription Drug Coverage. This program helps people with limited income and resources pay for their medicines. <br>  <br>  <b>Can I apply?</b><br>  You may get help from this program if you blind or disabled.  In addition, you must have limited income and resources.  Some resources such as your home, car, and certain portions of life insurance and burial accounts may not be counted when determining whether you meet the program guidelines. <br>  <br>  If you are a U.S. citizen and meet the other program guidelines, you may get help from this program. Some people who are not U.S. citizens may also take part in the program. You should contact the <a href="http://www.ssa.gov/pubs/11051.html" target="_blank"> Social Security Administration</a> for more information about SSI’s citizenship rules.<br>  <br>  <b>How do I apply?</b><br>  If you need help applying for SSI, Human Arc, a partner of the National Council on Aging, can help you apply for the program.  Human Arc&rsquo;s professional Disability Specialists can help with first-time applications, appeals and denials.  You can contact a Human Arc Disability Specialist by calling or visiting their Web site below.<br>    <img src="https://www.benefitscheckup.org/cf/img/partners/logo_humanarc.gif"><br>  <b>Human Arc</b><br>  Toll-free: (888) 825-1544  <br>Web site: [[track|humanarc|http://www.humanarc.com/disability/referrals.html?ekfrm=692]]  <br>  <br>  <b>Please note:</b>  The Social Security Administration (SSA) counts the date of a request for benefits as the filing date of the application. This is important because the date of the application will determine when your benefits start.  Unless you can submit a full application today, you should call SSA immediately and say that you want to apply for Supplemental Security Income benefits.  After the call, you can send them a letter like this: <a href="http://www.benefitscheckup.org/cf/frmssiprotected.pdf" target="_blank">Protected Filing Date Letter</a>.  You must submit a completed application to SSA within 60 days of the date of your request in order to get program benefits.'
WHERE display_id = 81234
AND language_id = 'EN';
</cfquery>

<cfquery dataSource="#APPLICATION.dsn#">
UPDATE display_language
SET display_text = '<b>How can this program help me?</b><br>  Supplemental Security Income (SSI) is a federal program that provides cash benefits every month if you meet the program guidelines.  The amount you get will be determined by the amount of income you receive from other sources and your living arrangements.  The purpose of the program is to make sure you have a minimum level of income so that you can pay for basic needs such as: food, clothing, and shelter. <br>  <br>  <b>Please note:</b>  If you enroll in both Medicare and SSI, you will be signed up for the Extra Help program through Medicare Prescription Drug Coverage. This program helps people with limited income and resources pay for their medicines. <br>  <br>  <b>Can I apply?</b><br>  You may get help from this program if you blind or disabled.  In addition, you must have limited income and resources.  Some resources such as your home, car, and certain portions of life insurance and burial accounts may not be counted when determining whether you meet the program guidelines. <br>  <br>  If you are a U.S. citizen and meet the other program guidelines, you may get help from this program. Some people who are not U.S. citizens may also take part in the program. You should contact the <a href="http://www.ssa.gov/pubs/11051.html" target="_blank"> Social Security Administration</a> for more information about SSI’s citizenship rules.<br>  <br>  <b>How do I apply?</b><br>  If you need help applying for SSI, Human Arc, a partner of the National Council on Aging, can help you apply for the program.  Human Arc&rsquo;s professional Disability Specialists can help with first-time applications, appeals and denials.  You can contact a Human Arc Disability Specialist by calling or visiting their Web site below.<br>    <img src="https://www.benefitscheckup.org/cf/img/partners/logo_humanarc.gif"><br>  <b>Human Arc</b><br>  Toll-free: (888) 825-1544  <br>Web site: [[track|humanarc|http://www.humanarc.com/disability/referrals.html?ekfrm=692]]  <br>  <br>  <b>Please note:</b>  The Social Security Administration (SSA) counts the date of a request for benefits as the filing date of the application. This is important because the date of the application will determine when your benefits start.  Unless you can submit a full application today, you should call SSA immediately and say that you want to apply for Supplemental Security Income benefits.  After the call, you can send them a letter like this: <a href="http://www.benefitscheckup.org/cf/frmssiprotected.pdf" target="_blank">Protected Filing Date Letter</a>.  You must submit a completed application to SSA within 60 days of the date of your request in order to get program benefits.'
WHERE display_id = 81236
AND language_id = 'EN';
</cfquery>
